const String appGroupId = 'group.dmytrowidget';
const String iOSWidgetName = 'WeatherWidgets';
const String androidWidgetName = 'WeatherWidget';
const int weatherRefreshDelayMinutes = 60;
const String developerDomain = 'turskyi.com';
const String supportEmail = 'support@$developerDomain';
const String imagePath = 'assets/images/';
const String appName = 'WeatherFit';
const String googlePlayUrl =
    'https://play.google.com/store/apps/details?id=com.turskyi.weather_fit';
