name: Build & upload to Firebase App Distribution
on:
  push:
    branches-ignore:
      - master

jobs:
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Write google-services.json file
        run: |
          cd android/app
          echo $GOOGLE_SERVICES | base64 -d > google-services.json
        shell: bash
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}

      - name: Write .env file
        run: |
          echo $ENV | base64 -d > .env
        shell: bash
        env:
          ENV: ${{ secrets.ENV }}

      - name: Write key.properties file
        run: |
          echo $KEY_PROPERTIES | base64 -d > android/key.properties
        shell: bash
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

      - name: Create keystore folder
        run: mkdir -p android/keystore

      - name: Write weather_fit_release.keystore file
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
        run: |
          echo $RELEASE_KEYSTORE | base64 --decode > android/keystore/weather_fit_release.keystore

      - name: Write weather_fit_debug.keystore file
        run: |
          echo $DEBUG_KEYSTORE | base64 -d > android/keystore/weather_fit_debug.keystore
        shell: bash
        env:
          DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get

      - name: Write env.g.dart file
        run: |
          dart run build_runner build --delete-conflicting-outputs
        shell: bash

      - run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: apk-build
          path: build/app/outputs/apk/release
  beta_apk:
    name: Upload Android Beta version to Firebase App Distribution
    needs: [ build_apk ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: apk-build
      - name: Display structure of downloaded files
        run: ls -R
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: app-release.apk